# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ControleFolios
                                 A QGIS plugin
 ce plugin permet de contrôler les données afin de les intégrer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-25
        copyright            : (C) 2026 by SRD
        email                : imane.belhafiane@srd-energies.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ControleFolios class from file ControleFolios.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Controle import ControleFolios
    return ControleFolios(iface)
