# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ControleFoliosDockWidget
                                 A QGIS plugin
 ce plugin permet de contrôler les données afin de les intégrer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-25
        git sha              : $Format:%H$
        copyright            : (C) 2026 by SRD
        email                : imane.belhafiane@srd-energies.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsProject
from qgis.core import NULL
from qgis.utils import iface
from qgis.PyQt.QtWidgets import QToolButton
from qgis.PyQt.QtWidgets import QProgressBar

import pandas as pd
import numpy as np

from qgis.core import QgsMessageLog, Qgis
from qgis.PyQt.QtWidgets import QApplication

# Figures
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from qgis.core import QgsDataSourceUri, QgsVectorLayer, QgsLayerTreeGroup
import warnings

# Importer les fonctions des comparaisons
from .core.connexion import connecter
from .core.comparaisons import comparer, df
from .core.rafraichissement import rafraichir

warnings.filterwarnings("ignore", category=DeprecationWarning)

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Controle_dockwidget_base.ui'))


class ControleFoliosDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(ControleFoliosDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

        # --------Variables des couches de comparaison
        self.precisions={1:1,2:5,3:10,4:50,5:100}

        

        # Les nom des groupe et des couches dans le projet
        self.nouveau_reseau_group = "NOUVEAU RECOLEMENT"
        self.reseau_existant_group = "RECOLEMENT EXISTANT"
        self.nouvelle_topo_group = "NOUVELLE TOPO"
        self.topo_existante_group = "TOPO EXISTANTE"

        self.nouvelle_schema = "recolement"
        self.ancienne_schema = ""

        self.groupe_comparaison2="COMPARAISON COPIE"
        self.groupe_comparaison="COMPARAISON"
        self.croisement_lignes_nom="bd_croisement_lignes"
        self.croisement_points_nom="bd_croisement_points"
        self.croisement_polygones_nom="bd_croisement_polygones"

        self.lignes={'topo':pd.DataFrame(),'elec':pd.DataFrame(),'ep':pd.DataFrame(),'gaz':pd.DataFrame()}
        self.points={'topo':pd.DataFrame(),'elec':pd.DataFrame(),'ep':pd.DataFrame(),'gaz':pd.DataFrame()}
        self.polygones={'topo':pd.DataFrame()}

        self.layer_lignes = None
        self.layer_points = None
        self.layer_polygones = None

        self.croisement_lignes=None
        self.croisement_points=None
        self.croisement_polygones=None

        # ---------Variables du plugin
        self.niveau="topo"
        self.projet.setEnabled(False)
        self.nouveau.setEnabled(False)
        self.ListProjets = []
        self.TrueClasses = [False,True,False,False,False]
        self.ListClasses = ["nouveau","annee","mois","moeuvre","projet"]

        self.selected_classe = None
        self.classes = None
        self.tables_graph = {}
        self.selected_table=None
        self.selected_state=None
        self.selected_objets = pd.DataFrame()
        self.mapping = {} #????

        self.selected_layer=None
        self.selected_ids=[]
        self.selected_objets_by_ids = None
        self.current_table_widget = None
        self.columns = []
        self.columns_details={}

        # ---------Variables des graphes
        # ----1
        self.figure_general = Figure()
        self.canvas_general = FigureCanvas(self.figure_general)
        layout_general = QtWidgets.QVBoxLayout(self.graphe_general)
        layout_general.addWidget(self.canvas_general)
        # ----2
        self.figure_tables = Figure()
        self.canvas_tables = FigureCanvas(self.figure_tables)
        layout_tables = QtWidgets.QVBoxLayout(self.tables)
        layout_tables.addWidget(self.canvas_tables)
        self.toolbar = NavigationToolbar(self.canvas_tables, self)
        self.layout().addWidget(self.toolbar)
        # ----3
        self.figure_attributs = Figure()
        self.canvas_attributs = FigureCanvas(self.figure_attributs)
        layout_attributs = QtWidgets.QVBoxLayout(self.attributs)
        layout_attributs.addWidget(self.canvas_attributs)

        
        self.GROUP_NAME = ""
        self.GROUP_NAME2 = ""


        
        self.set_label_precision()
        #self.chemain_comparaison()

        self.initialiser_affichage()
        

        self.horizontalSlider_precision.valueChanged.connect(self.set_label_precision)
        self.pushButton_comparaison.clicked.connect(self.comparaison)

        # Les niveaux 
        self.radioTOPO.toggled.connect(self.TOPO)
        self.radioELEC.toggled.connect(self.ELEC)
        self.radioEP.toggled.connect(self.EP)
        self.radioGAZ.toggled.connect(self.GAZ)

        # Les classes
        self.annee.stateChanged.connect(self.update_classes)
        self.mois.stateChanged.connect(self.update_classes)
        self.entreprise.stateChanged.connect(self.update_classes)
        self.projet.stateChanged.connect(self.update_classes)
        self.nouveau.currentTextChanged.connect(self.update_classes)

    
        self.attributs_details.currentTextChanged.connect(self.visualiser_details)
    def initialiser_affichage(self):
        self.get_croisement()
        self.set_graphe_general()
        self.listProjets()
        self.set_theme_comparaion()
        #self.controle_admissibilite()
        self.copier_group()


    def chemain_comparaison(self):
        user_profile = os.environ.get("USERPROFILE")
        gpkg_path = os.path.join(
            user_profile,
            "AppData",
            "Roaming",
            "QGIS",
            "QGIS3",
            "profiles",
            "default",
            "python",
            "plugins",
            "controle",
            "core",
            "gestfolio_temp",
            "bd_croisement_gestfolio.gpkg"
        )
        gpkg_path2 = os.path.join(
            user_profile,
            "AppData",
            "Roaming",
            "QGIS",
            "QGIS3",
            "profiles",
            "default",
            "python",
            "plugins",
            "controle",
            "core",
            "gestfolio_temp",
            "bd_folios_gestfolio.gpkg"
        )
        gpkg_path = gpkg_path.replace("\\", "/")
        root = QgsProject.instance().layerTreeRoot()
        group = root.findGroup(self.groupe_comparaison)

        for child in group.children():
            layer = child.layer()
            if layer:
                if layer.name() == 'bd_folios_gestfolio':
                    # 1. Sauvegarder le renderer
                    renderer = layer.renderer().clone()

                    # 2. Changer la source
                    new_source = f"{gpkg_path2}|layername=bd_folios_gestfolio"
                    layer.setDataSource(new_source, layer.name(), "ogr")

                    # 3. Restaurer le renderer
                    layer.setRenderer(renderer)
                    layer.triggerRepaint()
                else :
                    # 1. Sauvegarder le renderer
                    renderer = layer.renderer().clone()

                    # 2. Changer la source
                    new_source = f"{gpkg_path}|layername=bd_croisement_gestfolio"
                    layer.setDataSource(new_source, layer.name(), "ogr")

                    # 3. Restaurer le renderer
                    layer.setRenderer(renderer)
                    layer.triggerRepaint()
        group = root.findGroup(self.groupe_comparaison2)

        for child in group.children():
            layer = child.layer()
            if layer:
                if layer.name() == 'bd_folios_gestfolio':
                    # 1. Sauvegarder le renderer
                    renderer = layer.renderer().clone()

                    # 2. Changer la source
                    new_source = f"{gpkg_path2}|layername=bd_folios_gestfolio"
                    layer.setDataSource(new_source, layer.name(), "ogr")

                    # 3. Restaurer le renderer
                    layer.setRenderer(renderer)
                    layer.triggerRepaint()
                else :
                    # 1. Sauvegarder le renderer
                    renderer = layer.renderer().clone()

                    # 2. Changer la source
                    new_source = f"{gpkg_path}|layername=bd_croisement_gestfolio"
                    layer.setDataSource(new_source, layer.name(), "ogr")

                    # 3. Restaurer le renderer
                    layer.setRenderer(renderer)
                    layer.triggerRepaint()
        # Faire la meme chose pour le masque 


    def copier_group(self):
        self.GROUP_NAME = "RECOLEMENT EXISTANT"
        self.GROUP_NAME2 = "NOUVEAU RECOLEMENT"
        self.ancienne_schema = 'sw_pr_res'
        self.nouvelle_schema = 'recolement'
        self.project = QgsProject.instance()
        root = self.project.layerTreeRoot()

        source_group = root.findGroup(self.GROUP_NAME)
        target_group = root.findGroup(self.GROUP_NAME2)
        if target_group :
            parent = target_group.parent()
            parent.removeChildNode(target_group)
        if source_group:
            self.clone_group(source_group, root)
        
        self.GROUP_NAME = "TOPO EXISTANTE"
        self.GROUP_NAME2 = "NOUVELLE TOPO"
        self.ancienne_schema = 'sw_pr_topo'
        self.project = QgsProject.instance()
        root = self.project.layerTreeRoot()

        source_group = root.findGroup(self.GROUP_NAME)
        target_group = root.findGroup(self.GROUP_NAME2)
        if target_group :
            parent = target_group.parent()
            parent.removeChildNode(target_group)
        if source_group:
            self.clone_group(source_group, root)
        
    
    def clone_group(self, group, parent):
        OLD_SCHEMA = self.ancienne_schema
        NEW_SCHEMA = self.nouvelle_schema
        if group.name() == self.GROUP_NAME :
            new_group = parent.addGroup(self.GROUP_NAME2)
        else :
            new_group = parent.addGroup(group.name())

        for child in group.children():

            if isinstance(child, QgsLayerTreeGroup):
                self.clone_group(child, new_group)

            else:
                layer = child.layer()
                if not layer:
                    continue

                uri = QgsDataSourceUri(layer.source())

                schema = uri.schema()
                table = uri.table()
                geom_col = uri.geometryColumn()

                if schema != OLD_SCHEMA:
                    continue

                # 👉 adapter la colonne géométrique
                if geom_col == "the_geom":
                    new_geom_col = "geom"
                else:
                    new_geom_col = geom_col

                new_uri = QgsDataSourceUri(uri)
                new_uri.setDataSource(
                    NEW_SCHEMA,
                    table,
                    new_geom_col,  
                    uri.sql(),
                    uri.keyColumn()
                )

                new_layer = QgsVectorLayer(
                    new_uri.uri(False),
                    layer.name(),
                    "postgres"
                )

                if new_layer.isValid():

                    # Copier style + étiquettes
                    new_layer.setRenderer(layer.renderer().clone())

                    if layer.labeling():
                        new_layer.setLabeling(layer.labeling().clone())
                        new_layer.setLabelsEnabled(layer.labelsEnabled())

                    self.project.addMapLayer(new_layer, False)
                    new_group.addLayer(new_layer)

                
        return new_group
    # -------------------------------------------- Graphe général --------------------------------------------
    def set_graphe_general(self):

        niveau = self.niveau

        n=5
        if niveau=='topo':
            n=4


        if not self.lignes[niveau].empty:
            self.lignes[niveau]["classe"]=''
            if niveau!='topo' and self.TrueClasses[0]:
                self.lignes[niveau]["classe"]= np.where(
                                            self.lignes[niveau]['projet'] == self.nouveau.currentText(),
                                            '**',
                                            '' 
                                            )
            for i in range( 1,n):
                if self.TrueClasses[i]:
                    self.lignes[niveau]["classe"] += "|" + self.lignes[niveau][self.ListClasses[i]].astype(str)
            if True in self.TrueClasses :
                pass
            else :
                self.lignes[niveau]["classe"] = 'Général'
            grp_lignes = self.lignes[niveau].groupby(["classe", "croisement"])["valeur"].sum().unstack(fill_value=0)
        else:
            grp_lignes = pd.DataFrame()

        if not self.points[niveau].empty:
            self.points[niveau]["classe"]=''
            if niveau!='topo' and self.TrueClasses[0]:
                self.points[niveau]["classe"]= np.where(
                                            self.points[niveau]['projet'] == self.nouveau.currentText(),
                                            '**',
                                            '' 
                                            )
            for i in range( 1,n ):
                if self.TrueClasses[i]:
                    self.points[niveau]["classe"] += "|" + self.points[niveau][self.ListClasses[i]].astype(str)
            if True in self.TrueClasses :
                pass
            else :
                self.points[niveau]["classe"] = 'Général'
            grp_points = self.points[niveau].groupby(["classe", "croisement"])["valeur"].sum().unstack(fill_value=0)
        else:
            grp_points = pd.DataFrame()

        if niveau=='topo' and not self.polygones[niveau].empty:
            self.polygones[niveau]["classe"]=''
            if niveau!='topo' and self.TrueClasses[0]:
                self.polygones[niveau]["classe"]= np.where(
                                            self.polygones[niveau]['projet'] == self.nouveau.currentText(),
                                            '**',
                                            '' 
                                            )
            for i in range( 1,n ):
                if self.TrueClasses[i]:
                    self.polygones[niveau]["classe"] += "|" + self.polygones[niveau][self.ListClasses[i]].astype(str)
            if True in self.TrueClasses :
                pass
            else :
                self.polygones[niveau]["classe"] = 'Général'
            grp_polygones = self.polygones[niveau].groupby(["classe", "croisement"])["valeur"].sum().unstack(fill_value=0)
        else:
            grp_polygones = pd.DataFrame()
        if grp_lignes.empty and grp_points.empty and grp_polygones.empty:
            self.figure_general.clear()
            self.canvas_general.draw()
            self.figure_tables.clear()
            self.canvas_tables.draw()
            return
            # projets communs
        projets = sorted(set(grp_lignes.index).union(grp_points.index).union(grp_polygones.index))
        grp_lignes = grp_lignes.reindex(projets, fill_value=0)
        grp_points = grp_points.reindex(projets, fill_value=0)
        grp_polygones = grp_polygones.reindex(projets, fill_value=0)

            # ---------------- CONFIGURATION DU PLOT ----------------
        self.figure_general.clear()
        ax = self.figure_general.add_subplot(111)
        ax2 = ax.twiny()  # axe haut pour points et polygones

        y = np.arange(len(projets))
        height = 0.19
        gap = 0.12 # petit écart vertical entre barres

        couleurs = {
            "CONSERVATION_IDENTIQUE": "#074A69",
            "CONSERVATION_MODIFIEE": "#048B9A",
            "CREATION": "#10b642",
            "SUPPRESSION": "#c74747"
        }

        espace = 0
        height2=0
        self.general_bars = {}
        # BARRES POLYGONES (axe haut) 
        if not grp_polygones.empty:
            left_poly = np.zeros(len(projets))
            for col in grp_polygones.columns:
                vals = grp_polygones[col].values
                bars = ax2.barh(y + height/2 + gap , vals, height,
                        left=left_poly,
                        color=couleurs.get(col, "gray"))
                for i, bar in enumerate(bars):
                    self.general_bars[bar] = {
                        "table": projets[i]
                    }
                left_poly += vals
        else : 
            espace = height/2 + gap
            height2 = 0.07

        # BARRES LIGNES (axe bas) 
        if not grp_lignes.empty:
            left_l = np.zeros(len(projets))
            for col in grp_lignes.columns:
                vals = grp_lignes[col].values
                bars = ax.barh(y - height/2 - gap + height2, vals, height + height2,
                        left=left_l,
                        color=couleurs.get(col, "gray"),
                        label=col)
                for i, bar in enumerate(bars):
                    self.general_bars[bar] = {
                        "table": projets[i]
                    }
                left_l += vals

        # BARRES POINTS (axe haut)
        if not grp_points.empty:
            left_p = np.zeros(len(projets))
            for col in grp_points.columns:
                vals = grp_points[col].values
                bars = ax2.barh(y + espace - height2, vals, height + height2,
                        left=left_p,
                        color=couleurs.get(col, "gray"))
                for i, bar in enumerate(bars):
                    self.general_bars[bar] = {
                        "table": projets[i]
                    }
                left_p += vals

        

        # AJOUT DES SYMBOLES
        symbols = {
            "ligne": "▬",
            "point": "●",
            "polygone": "■"
        }
        symbol_size = 7
        for i in range(len(projets)):
            if not grp_lignes.empty:
                ax.text(left_l[i], y[i] - height/2 - gap + height2, symbols["ligne"], va='center', fontsize=symbol_size)
            if not grp_points.empty:
                ax2.text(left_p[i], y[i]+ espace - height2, symbols["point"], va='center', fontsize=symbol_size)
            if not grp_polygones.empty:
                ax2.text(left_poly[i], y[i] + height/2 + gap + 0.01, symbols["polygone"], va='center', fontsize=symbol_size)

        # AXES
        ax.set_yticks(y)
        ax.set_yticklabels(projets)
        ax.set_xlabel("Longueur (lignes)")
        ax2.set_xlabel("Nombre d'objets (points & polygones)")
        ax.set_title(f"Croisements  ({niveau})")

        # LÉGENDE UNIQUE
        '''handles, labels = ax.get_legend_handles_labels()
        unique = dict(zip(labels, handles))
        ax.legend(
            unique.values(),
            unique.keys(),
            loc='best',
            #bbox_to_anchor=(0.8, 1.3), # met tout sur une ligne
            frameon=False
        )'''

        self.figure_general.tight_layout()
        self.canvas_general.draw()
        self.canvas_general.mpl_connect("button_press_event", self.on_click_general)
        self.selected_classe = None
        self.classes = projets
        self.filtre_niveau()
        self.set_graphe_tables()
        

    def set_theme_comparaion(self):
        project = QgsProject.instance()
        theme_collection = project.mapThemeCollection()

        theme_name = "COMPARAISON"

        root = project.layerTreeRoot()
        model = iface.layerTreeView().layerTreeModel()  

        theme_collection.applyTheme(theme_name, root, model)

        iface.mapCanvas().refresh()
    def set_theme(self):
        root = QgsProject.instance().layerTreeRoot()

        for group in root.children():
            if not isinstance(group, QgsLayerTreeGroup):
                continue

            name = group.name()

            # 🔵 CAS 1 : niveau = topo
            if self.niveau == 'topo':
                if name == "NOUVELLE TOPO":
                    self._set_visible_recursive(group, True)
                elif name == "Masque":
                    pass
                else:
                    group.setItemVisibilityChecked(False)

            # 🟢 CAS 2 : autre niveau
            else:
                if name == "NOUVEAU RECOLEMENT":
                    for child in group.children():
                        if isinstance(child, QgsLayerTreeGroup):
                            if child.name().upper() == self.niveau.upper():
                                self._set_visible_recursive(child, True)
                            elif child.name() == "Masque":
                                pass
                            else:
                                child.setItemVisibilityChecked(False)

                    group.setItemVisibilityChecked(True)  # important pour voir les enfants

                elif name == "Masque":
                    pass

                else:
                    group.setItemVisibilityChecked(False)
    def _set_visible_recursive(self, group, visible):
        group.setItemVisibilityChecked(visible)

        for child in group.children():
            if isinstance(child, QgsLayerTreeGroup):
                self._set_visible_recursive(child, visible)
            else:
                child.setItemVisibilityChecked(visible)
    def set_theme1(self):
        project = QgsProject.instance()
        theme_collection = project.mapThemeCollection()

        theme_name = self.niveau.upper()

        root = project.layerTreeRoot()
        model = iface.layerTreeView().layerTreeModel()  

        theme_collection.applyTheme(theme_name, root, model)

        iface.mapCanvas().refresh()

    def on_click_general(self, event):
        if event.ydata is None:
            return

        y_index = int(round(event.ydata))

        if y_index < 0 or y_index >= len(self.classes):
            return

        if self.selected_classe != self.classes[y_index] :
            self.selected_classe = self.classes[y_index]
        else :
            self.selected_classe = None
        self.set_graphe_tables()
        if self.selected_classe :
            self.filtre()
        else :
            self.non_filtre()
        for bar, info in self.general_bars.items():
            if self.selected_classe is None :
                bar.set_alpha(1.0)  # barre sélectionnée
            elif info["table"] != self.selected_classe:
                bar.set_alpha(0.2)  # barre non sélectionnée
            else:
                bar.set_alpha(1.0) 
        self.canvas_general.draw()

        
    def filtre(self) :
        filtre_conditions = self.selected_classe.split("|")
        
        i=1
        conditions=[]
        if self.TrueClasses[0] :
            conditions.append(f'"projet" = \'{self.nouveau.currentText()}\'')
        if self.TrueClasses[2] :
            conditions.append(f'"mois" = \'{filtre_conditions[i]}\'')
            i = i+1
        elif self.TrueClasses[1] :
            conditions.append(f'"annee" = \'{filtre_conditions[i]}\'')
            i = i+1
        if self.TrueClasses[3] :
            conditions.append(f'"moeuvre" = \'{filtre_conditions[i]}\'')
            i+1
        if self.TrueClasses[4] :
            conditions.append(f'"projet" = \'{filtre_conditions[i]}\'')
            i+1

        conditions.append(f'"grpe_objet" = \'{self.niveau}\'')
        expr = " and ".join(conditions)
        self.layer_lignes.setSubsetString(expr)
        self.layer_points.setSubsetString(expr)
        self.layer_polygones.setSubsetString(expr)
        
    def filtre_niveau(self) :
        self.layer_lignes.setSubsetString(f'"grpe_objet" = \'{self.niveau}\'')
        self.layer_points.setSubsetString(f'"grpe_objet" = \'{self.niveau}\'')
        self.layer_polygones.setSubsetString(f'"grpe_objet" = \'{self.niveau}\'')
    def non_filtre(self) :
        self.layer_lignes.setSubsetString('')
        self.layer_points.setSubsetString('')
        self.layer_polygones.setSubsetString('')

    # -------------------------------------------- Graphe des Tables --------------------------------------------
    
    def set_graphe_tables(self):
        niveau = self.niveau
        df_lignes = self.lignes[niveau].copy()
        df_points = self.points[niveau].copy()
        if niveau == 'topo':
            df_polygones = self.polygones[niveau].copy()
        else :
            df_polygones = pd.DataFrame()

        # ---------------- GROUPEMENT PAR TABLE_NAME ET CROISEMENT ----------------
        if not df_lignes.empty: 
            if self.selected_classe is not None:
                df_lignes['croisement'] = np.where(
                        df_lignes['classe'] == self.selected_classe,
                        df_lignes['croisement'],  
                        'NOT_SELECTED'            
                    )
            grp_lignes = df_lignes.groupby(["table_name", "croisement"])["valeur"].sum().unstack(fill_value=0)
            grp_lignes['total'] = grp_lignes.sum(axis=1)
            
            # Trie par la colonne total décroissante
            grp_lignes = grp_lignes.sort_values(by='total')
            
            # Supprime la colonne temporaire total
            grp_lignes = grp_lignes.drop(columns='total')
        else:
            grp_lignes = pd.DataFrame()

        if not df_points.empty:
            if self.selected_classe is not None:
                df_points['croisement'] = np.where(
                        df_points['classe'] == self.selected_classe,
                        df_points['croisement'],  
                        'NOT_SELECTED'            
                    )
            grp_points = df_points.groupby(["table_name", "croisement"])["valeur"].sum().unstack(fill_value=0)
            grp_points['total'] = grp_points.sum(axis=1)
            
            # Trie par la colonne total décroissante
            grp_points = grp_points.sort_values(by='total')
            # Supprime la colonne temporaire total
            grp_points = grp_points.drop(columns='total')
        else:
            grp_points = pd.DataFrame()

        if not df_polygones.empty:
            if self.selected_classe is not None:
                df_polygones['croisement'] = np.where(
                        df_polygones['classe'] == self.selected_classe,
                        df_polygones['croisement'],  
                        'NOT_SELECTED'            
                    )
            grp_polygones = df_polygones.groupby(["table_name", "croisement"])["valeur"].sum().unstack(fill_value=0)
            grp_polygones['total'] = grp_polygones.sum(axis=1)
            
            # Trie par la colonne total décroissante
            grp_polygones = grp_polygones.sort_values(by='total')
            
            # Supprime la colonne temporaire total
            grp_polygones = grp_polygones.drop(columns='total')
        else:
            grp_polygones = pd.DataFrame()

        # ---------------- PROJETS COMMUNS ----------------
        tables = list(grp_lignes.index) + list(grp_points.index) + list(grp_polygones.index)
        grp_polygones = grp_polygones.reindex(tables, fill_value=0)
        grp_points = grp_points.reindex(tables, fill_value=0)
        grp_lignes = grp_lignes.reindex(tables, fill_value=0)
        # ---------------- CONFIGURATION DU PLOT ----------------
        self.figure_tables.clear()
        ax = self.figure_tables.add_subplot(111)
        ax2 = ax.twiny()  # axe haut pour points et polygones

        y = np.arange(len(tables))
        height = 0.70
        couleurs = {
            "CONSERVATION_IDENTIQUE": "#074A69",
            "CONSERVATION_MODIFIEE": "#048B9A",
            "CREATION": "#10b642",
            "SUPPRESSION": "#c74747",
            "NOT_SELECTED" :"#BDC5D0"
        }
        self.tables_graph={}
        # ---------------- BARRES POLYGONES (axe haut) ----------------
        if not grp_polygones.empty:
            left_poly = np.zeros(len(tables))
            for col in couleurs.keys():
                if col in grp_polygones.columns :
                    vals = grp_polygones[col].values
                    bars = ax2.barh(y, vals, height,
                            left=left_poly, color=couleurs.get(col, "#c9c2c1"), picker = True)
                    for i, bar in enumerate(bars):
                        self.tables_graph[bar] = {
                            "table": tables[i],
                            "classe": col,
                            "type_geom" :"polygone"
                        }
                    left_poly += vals

        # ---------------- BARRES POINTS (axe haut) ----------------
        if not grp_points.empty:
            left_p = np.zeros(len(tables))
            for col in couleurs.keys():
                if col in grp_points.columns :
                    vals = grp_points[col].values
                    bars = ax2.barh(y, vals, height,
                            left=left_p, color=couleurs.get(col, "#c9c2c1"), picker = True)
                    for i, bar in enumerate(bars):
                        self.tables_graph[bar] = {
                            "table": tables[i],
                            "classe": col,
                            "type_geom" :"point"
                        }
                    left_p += vals


        # ---------------- BARRES LIGNES (axe bas) ----------------
        if not grp_lignes.empty:
            left_l = np.zeros(len(tables))
            for col in couleurs.keys():
                if col in grp_lignes.columns :
                    vals = grp_lignes[col].values
                    bars = ax.barh(y, vals, height,
                            left=left_l, color=couleurs.get(col, "#c9c2c1"), label=col, picker = True)
                    for i, bar in enumerate(bars):
                        self.tables_graph[bar] = {
                            "table": tables[i],
                            "classe": col,
                            "type_geom" :"ligne"
                        }
                    left_l += vals

        # ---------------- AXES ----------------
        
        ax.set_yticks(y)
        ax.set_yticklabels(tables, fontsize=8)
        ax.set_xlabel("Longueur des lignes")
        ax2.set_xlabel("Nombre de points et polygones")
        ax.set_title(f"Objets par table et type de croisement ({self.niveau})")

        #ax.legend(title="Croisement")
        
        self.figure_tables.tight_layout()
        self.canvas_tables.draw()

        self.set_theme_comparaion()
        
        self.figure_attributs.clear()
        self.canvas_attributs.draw()
        self.attributs_details.clear()

        self.canvas_tables.mpl_connect("button_press_event", self.on_table)
    """def set_graphe_tables(self):
        niveau = self.niveau
        df_lignes = self.lignes[niveau].copy()
        df_points = self.points[niveau].copy()
        if niveau == 'topo':
            df_polygones = self.polygones[niveau].copy()
        else :
            df_polygones = pd.DataFrame()
        if df_lignes.empty and df_points.empty and df_polygones.empty:
            return

        # ---------------- GROUPEMENT PAR TABLE_NAME ET CROISEMENT ----------------
        if not df_lignes.empty: 
            if self.selected_classe is not None:
                df_lignes['croisement'] = np.where(
                        df_lignes['classe'] == self.selected_classe,
                        df_lignes['croisement'],  
                        'NOT_SELECTED'            
                    )
            grp_lignes = df_lignes.groupby(["table_name", "croisement"])["valeur"].sum().unstack(fill_value=0)
            grp_lignes['total'] = grp_lignes.sum(axis=1)
            
            # Trie par la colonne total décroissante
            grp_lignes = grp_lignes.sort_values(by='total')
            
            # Supprime la colonne temporaire total
            grp_lignes = grp_lignes.drop(columns='total')
        else:
            grp_lignes = pd.DataFrame()

        if not df_points.empty:
            if self.selected_classe is not None:
                df_points['croisement'] = np.where(
                        df_points['classe'] == self.selected_classe,
                        df_points['croisement'],  
                        'NOT_SELECTED'            
                    )
            grp_points = df_points.groupby(["table_name", "croisement"])["valeur"].sum().unstack(fill_value=0)
            grp_points['total'] = grp_points.sum(axis=1)
            
            # Trie par la colonne total décroissante
            grp_points = grp_points.sort_values(by='total')
            # Supprime la colonne temporaire total
            grp_points = grp_points.drop(columns='total')
        else:
            grp_points = pd.DataFrame()

        if not df_polygones.empty:
            if self.selected_classe is not None:
                df_polygones['croisement'] = np.where(
                        df_polygones['classe'] == self.selected_classe,
                        df_polygones['croisement'],  
                        'NOT_SELECTED'            
                    )
            grp_polygones = df_polygones.groupby(["table_name", "croisement"])["valeur"].sum().unstack(fill_value=0)
            grp_polygones['total'] = grp_polygones.sum(axis=1)
            
            # Trie par la colonne total décroissante
            grp_polygones = grp_polygones.sort_values(by='total')
            
            # Supprime la colonne temporaire total
            grp_polygones = grp_polygones.drop(columns='total')
        else:
            grp_polygones = pd.DataFrame()

        # ---------------- PROJETS COMMUNS ----------------
        tables = list(grp_lignes.index) + list(grp_points.index) + list(grp_polygones.index)
        grp_polygones = grp_polygones.reindex(tables, fill_value=0)
        grp_points = grp_points.reindex(tables, fill_value=0)
        grp_lignes = grp_lignes.reindex(tables, fill_value=0)
        # ---------------- CONFIGURATION DU PLOT ----------------
        self.figure_tables.clear()

        gs = self.figure_tables.add_gridspec(2, 1, height_ratios=[3, 1])

        ax = self.figure_tables.add_subplot(gs[0])
        ax2 = ax.twiny()
        ax_geo = self.figure_tables.add_subplot(gs[1])

        height = 0.70

        couleurs = {
            "CONSERVATION_IDENTIQUE": "#074A69",
            "CONSERVATION_MODIFIEE": "#048B9A",
            "CREATION": "#10b642",
            "SUPPRESSION": "#c74747",
            "NOT_SELECTED": "#BDC5D0"
        }

        self.tables_graph = {}

        geo_name = "geo_r_0_0_1"

        # =====================================================
        # 🔥 SPLIT SIMPLE DES TABLES
        # =====================================================
        tables_haut = [t for t in tables if t != geo_name]

        y = np.arange(len(tables_haut))

        # =====================================================
        # 🟢 FONCTION SAFE POUR RECUP VALEURS
        # =====================================================
        def get_vals(df, col):
            return [
                df[col].iloc[i] if col in df.columns else 0
                for i, t in enumerate(tables)
                if t != geo_name
            ]

        # =====================================================
        # 🟢 POLYGONES
        # =====================================================
        if not grp_polygones.empty:
            left_poly = np.zeros(len(tables_haut))

            for col in couleurs:
                if col in grp_polygones.columns:
                    vals = get_vals(grp_polygones, col)

                    bars = ax2.barh(
                        y, vals, height,
                        left=left_poly,
                        color=couleurs[col],
                        picker=True
                    )

                    for i, bar in enumerate(bars):
                        self.tables_graph[bar] = {
                            "table": tables_haut[i],
                            "classe": col,
                            "type_geom": "polygone"
                        }

                    left_poly += vals

        # =====================================================
        # 🟢 POINTS
        # =====================================================
        if not grp_points.empty:
            left_p = np.zeros(len(tables_haut))

            for col in couleurs:
                if col in grp_points.columns:
                    vals = get_vals(grp_points, col)

                    bars = ax2.barh(
                        y, vals, height,
                        left=left_p,
                        color=couleurs[col],
                        picker=True
                    )

                    for i, bar in enumerate(bars):
                        self.tables_graph[bar] = {
                            "table": tables_haut[i],
                            "classe": col,
                            "type_geom": "point"
                        }

                    left_p += vals

        # =====================================================
        # 🟢 LIGNES
        # =====================================================
        if not grp_lignes.empty:
            left_l = np.zeros(len(tables_haut))

            for col in couleurs:
                if col in grp_lignes.columns:
                    vals = get_vals(grp_lignes, col)

                    bars = ax.barh(
                        y, vals, height,
                        left=left_l,
                        color=couleurs[col],
                        picker=True
                    )

                    for i, bar in enumerate(bars):
                        self.tables_graph[bar] = {
                            "table": tables_haut[i],
                            "classe": col,
                            "type_geom": "ligne"
                        }

                    left_l += vals

        # =====================================================
        # 🔵 AXE HAUT
        # =====================================================
        ax.set_yticks(y)
        ax.set_yticklabels(tables_haut, fontsize=8)
        ax.set_xlabel("Longueur des lignes")
        ax2.set_xlabel("Points / Polygones")

        ax.set_title(f"Objets par table et type de croisement ({self.niveau})")

        # =====================================================
        # 🔥 ZOOM BAS (ULTRA SIMPLE ET FIABLE)
        # =====================================================

        geo_value = 0

        if geo_name in tables:

            left_l = 0

            for col in couleurs:

                if col in grp_points.columns:

                    geo_value = grp_points.loc[geo_name, col]

                    bars =ax_geo.barh(
                        geo_name,
                        geo_value,
                        height,
                        left=left_l,
                        color=couleurs[col],
                        picker=True
                    )
                    for i, bar in enumerate(bars):
                        self.tables_graph[bar] = {
                            "table": geo_name,
                            "classe": col,
                            "type_geom": "point"
                        }
                    left_l += geo_value

        else:
            ax_geo.text(0.5, 0.5, "geo_r_0_0_1 non trouvé",
                        ha='center', va='center')

        ax_geo.set_yticks([0])
        ax_geo.set_yticklabels([geo_name], fontsize=8)
        ax_geo.set_xlabel("Points GPS")
        ax_geo.grid(True, axis='x', alpha=0.3)

        # =====================================================
        # FINAL
        # =====================================================
        self.figure_tables.tight_layout()
        self.canvas_tables.draw()

        self.set_theme_comparaion()
        self.canvas_tables.mpl_connect("button_press_event", self.on_table)"""

    def on_table(self, event):
        for bar, info in self.tables_graph.items():
            contains, _ = bar.contains(event)
            if contains:
                self.selected_table=info['table']
                self.selected_state=info['classe']
                self.selected_geom=info['type_geom']
                
                #if self.selected_state != "SUPPRESSION":
                self.select_objets()
                self.get_layer()
                self.select_objets_by_ids()
                self.list_choix()
                self.set_theme()
                """else :
                    self.figure_attributs.clear()
                    self.canvas_attributs.draw()
                    self.attributs_details.clear()
                    self.set_theme_comparaion()"""
                break
    def list_choix(self):
        if self.selected_state == "CONSERVATION_MODIFIEE":
            self.list_methodes()
        else :
            self.list_attributs()
        """else :
            self.figure_attributs.clear()
            self.canvas_attributs.draw()
            self.attributs_details.clear()"""
    def visualiser_details(self):
        if self.selected_state == "CONSERVATION_MODIFIEE":
            self.visualiser_modifications()
        elif self.selected_state != "NOT_SELECTED":
            self.visualiser_attributs()
        

    def get_layer(self):
        if self.selected_layer :
            self.selected_layer.removeSelection()
        if self.selected_state !='SUPPRESSION':
            if self.niveau =='topo':
                groupe =QgsProject.instance().layerTreeRoot().findGroup(self.nouvelle_topo_group)
            else :
                groupe =QgsProject.instance().layerTreeRoot().findGroup(self.nouveau_reseau_group)
        else :
            if self.niveau =='topo':
                groupe =QgsProject.instance().layerTreeRoot().findGroup(self.topo_existante_group)
            else :
                groupe =QgsProject.instance().layerTreeRoot().findGroup(self.reseau_existant_group)
        if groupe:
            for layer in groupe.findLayers():
                    if layer.layer().name() == self.selected_table :
                        self.selected_layer= layer.layer()
                        break


    def list_methodes(self):
        self.attributs_details.clear()
        self.attributs_details.addItem("Attributs modifiés")
        self.attributs_details.addItem("Modifications")
        
    def select_objets(self):
        if self.selected_geom == 'ligne':
            table = self.lignes[self.niveau].copy()
            self.selected_objets = table[
                (table['table_name'] == self.selected_table) &
                ((table['classe'] == self.selected_classe) | (self.selected_classe is None)) &
                (table['croisement'] == self.selected_state)
            ]
        elif self.selected_geom == 'point':
            table = self.points[self.niveau].copy()
            self.selected_objets = table[
                (table['table_name'] == self.selected_table) &
                ((table['classe'] == self.selected_classe) | (self.selected_classe is None)) &
                (table['croisement'] == self.selected_state)
            ]
        elif self.selected_geom == 'polygone':
            table = self.polygones[self.niveau].copy()
            self.selected_objets = table[
                (table['table_name'] == self.selected_table) &
                ((table['classe'] == self.selected_classe) | (self.selected_classe is None)) &
                (table['croisement'] == self.selected_state)
            ]
        else :
            return
        if self.selected_state !='SUPPRESSION':
            self.selected_ids = set(self.selected_objets['gid_nouv'].astype(int).tolist())
        else :
            self.selected_ids = set(self.selected_objets['gid_ancie'].astype(int).tolist())
       
    def visualiser_modifications(self):
        methode = self.attributs_details.currentText()
        if methode == "Attributs modifiés" :
            attribut = 'attributs_modif'
            titre = 'attribut modifié'
        else :
            #methode =="Modifications":
            attribut = 'modifications'
            titre =  'modification'
        
        # Ne garder que les lignes où self.attribut n'est pas null
        df = self.selected_objets[pd.notnull(self.selected_objets[attribut])].copy()


        # Convertir en string (au cas où)
        df[attribut] = df[attribut].astype(str)

        # Séparer les valeurs par '|' et "exploser" en lignes individuelles
        df_exploded = df.assign(valeur_split = df[attribut].str.split('|')).explode('valeur_split')

        # Nettoyer les espaces
        df_exploded['valeur_split'] = df_exploded['valeur_split'].str.strip()

        # Faire la somme des colonnes 'valeur' groupée par chaque élément
        self.mapping = df_exploded.groupby('valeur_split')['valeur'].sum().to_dict()

        # tracer le diagramme horizontal
        self.figure_attributs.clear()
        ax = self.figure_attributs.add_subplot(111)

        

        # barres horizontales
        self.bars = ax.barh(list(self.mapping.keys()), list(self.mapping.values()),color = "#048B9A", picker=True)

        ax.set_title(self.selected_table)
        if self.selected_geom == 'ligne' :
            ax.set_xlabel('Longueur')
        else :
            ax.set_xlabel('Nombre')

        ax.set_ylabel(titre)    
        ax.tick_params(axis='y', labelrotation=0)  # rotation si nécessaire

        self.figure_attributs.tight_layout()
        self.canvas_attributs.draw()

    def select_objets_by_ids(self):
        QgsMessageLog.logMessage(f"comparaison projet - : {self.selected_ids}", "MonPlugin", Qgis.Info)
        # Liste des IDs à filtrer
        ids = self.selected_ids
        self.selected_layer.selectByIds(list(ids))
        iface.mapCanvas().zoomToSelected(self.selected_layer)
        # Crée une liste pour stocker les entités filtrées
        selected_features = []
        
        # Parcours toutes les entités du layer
        for feature in self.selected_layer.selectedFeatures():
            selected_features.append(feature)
        QgsMessageLog.logMessage(f"comparaison projet : {selected_features}", "MonPlugin", Qgis.Info)
        # Crée le DataFrame à partir des attributs
        rows = [f.attributes() for f in selected_features]
        self.columns = [field.name() for field in self.selected_layer.fields()]
        self.selected_objets_by_ids = pd.DataFrame(rows, columns=self.columns)
        # Ajouter la colonne de longueur géométrique
        details = []
        for feature in selected_features:
            geom = feature.geometry()
            if geom is not None:
                # Longueur pour polylignes, aire pour polygones
                if self.selected_geom == 'ligne':
                    details.append(geom.length())
                    #geom_lengths.append(geom.area())
                else:
                    details.append(1)  # points ou autre
            
        
        # 
        """self.selected_objets_by_ids['daterel'] = self.selected_objets_by_ids['daterel'].apply(
                lambda x: x.toString("dd/MM/yyyy") if x and hasattr(x, "toString") else None
            )"""
        
        self.selected_objets_by_ids['detail'] = details
        #self.selected_objets_by_ids = self.selected_objets_by_ids.replace([None, NULL, ''], 'NULL')
        widget=self.current_table_widget
        if widget is not None :
            widget.destroyed.disconnect(self.on_table_closed)
            widget.close()
        self.current_table_widget = iface.showAttributeTable(self.selected_layer)
        self.current_table_widget.destroyed.connect(self.on_table_closed)
        table_widget = self.current_table_widget
        if table_widget:
            # Cherche le bouton "Afficher sélection"
            buttons = table_widget.findChildren(QToolButton)
            
            for btn in buttons:
                if "sommet" in btn.toolTip().lower() and "sélection" in btn.toolTip().lower():
                    btn.click()
                    break
        
    def on_table_closed(self):
        self.current_table_widget = None
        
    def list_attributs(self):
        self.attributs_details.clear()
        self.columns_details = {}
        for column in self.columns :
            if column != 'gid':
                column_dict = {}
                column_dict = self.selected_objets_by_ids.groupby(column)['detail'].sum().to_dict()
                self.columns_details[column] = column_dict
                self.attributs_details.addItem(column)
        


    def visualiser_attributs(self):
        couleurs = {
            "CONSERVATION_IDENTIQUE": "#074A69",
            "CONSERVATION_MODIFIEE": "#048B9A",
            "CREATION": "#10b642",
            "SUPPRESSION": "#c74747",
            "NOT_SELECTED" :"#BDC5D0"
        }        
        column = self.attributs_details.currentText()
        if column != '':
            # tracer le diagramme horizontal
            self.figure_attributs.clear()
            ax = self.figure_attributs.add_subplot(111)
            keys = [
                "NULL" if k is None else str(k)
                for k in self.columns_details[column].keys()
            ]
            # barres horizontales
            self.bars = ax.barh(keys, list(self.columns_details[column].values()),color = couleurs[self.selected_state] , picker=True)

            ax.set_title(self.selected_table)
            if self.selected_geom == 'ligne' :
                ax.set_xlabel('Longueur')
            else :
                ax.set_xlabel('Nombre')

            ax.set_ylabel('')    
            ax.tick_params(axis='y', labelrotation=0)  # rotation si nécessaire

            self.figure_attributs.tight_layout()
            self.canvas_attributs.draw()

    # Paramètres du plugin
    def TOPO(self, checked):
        if checked :
            self.update_niveau(False,'topo')
    def ELEC(self, checked):
        if checked :
            self.update_niveau(True,'elec')
    def EP(self, checked):
        if checked :
            self.update_niveau(True,'ep')
    def GAZ(self, checked):
        if checked :
            self.update_niveau(True,'gaz')
    def update_niveau(self,visible,niveau) :
        self.niveau = niveau
        self.projet.setEnabled(visible)
        self.nouveau.setEnabled(visible)
        self.set_graphe_general()
        self.listProjets()

    def update_classes(self):
        
        self.TrueClasses[2] = self.mois.isChecked()
        self.TrueClasses[3] = self.entreprise.isChecked()
        self.TrueClasses[4] = self.projet.isChecked()
        if self.TrueClasses[2] : 
            self.TrueClasses[1] = False
        else :
            self.TrueClasses[1] = self.annee.isChecked()
        if self.nouveau.currentText() == 'Nouveau projet' :
            self.TrueClasses[0] = False
        else :
            self.TrueClasses[0] = True
        self.set_graphe_general()

    
    # -------------------------------------------- Lire des couches -------------------------------------------

    def get_croisement(self):
        groupe =QgsProject.instance().layerTreeRoot().findGroup(self.groupe_comparaison)
        if groupe:
            for layer in groupe.findLayers():
                    if layer.layer().name() == self.croisement_lignes_nom :
                        self.layer_lignes= layer.layer()
                    elif layer.layer().name() == self.croisement_points_nom :
                        self.layer_points= layer.layer()
                    elif layer.layer().name() == self.croisement_polygones_nom :
                        self.layer_polygones= layer.layer()
        self.non_filtre()

        if self.layer_lignes is None and self.layer_points is None and self.layer_polygones is None:
            return

        data_lignes = {niveau:[] for niveau in self.lignes}
        
        if self.layer_lignes is not None:
            cols = [field.name() for field in self.layer_lignes.fields()]
            for f in self.layer_lignes.getFeatures():
                if f["grpe_objet"] != 'NR':
                    d = dict(zip(cols, f.attributes()))
                    d["croisement"] = str(d["croisement"]).strip().upper()
                    d["valeur"] = f.geometry().length()
                    
                    data_lignes[f["grpe_objet"]].append(d)

        data_points = {niveau:[] for niveau in self.points}
        if self.layer_points is not None:
            cols = [field.name() for field in self.layer_points.fields()]
            for f in self.layer_points.getFeatures():
                if f["grpe_objet"] != 'NR':
                    d = dict(zip(cols, f.attributes()))
                    d["croisement"] = str(d["croisement"]).strip().upper()
                    d["valeur"] = 1
                    
                    data_points[f["grpe_objet"]].append(d)

        data_polygones  = {niveau:[] for niveau in self.polygones}
        if self.layer_polygones is not None:
            cols = [field.name() for field in self.layer_polygones.fields()]
            for f in self.layer_polygones.getFeatures():
                if f["grpe_objet"] != 'NR':
                    d = dict(zip(cols, f.attributes()))
                    d["croisement"] = str(d["croisement"]).strip().upper()
                    d["valeur"] = 1
                    
                    data_polygones[f["grpe_objet"]].append(d)

        for niveau in data_lignes :
            self.lignes[niveau] = pd.DataFrame(data_lignes[niveau])
        for niveau in data_points :
            self.points[niveau] = pd.DataFrame(data_points[niveau])
        for niveau in data_polygones :
            self.polygones[niveau] = pd.DataFrame(data_polygones[niveau])

        
    
    
    def listProjets(self):
        if self.niveau == 'topo' :
            self.nouveau.clear()
            self.nouveau.addItem("Nouveau projet")
            self.ListProjets=[]
        else:
            projets = set()

            # Parcours lignes
            if not self.lignes[self.niveau].empty:
                projets.update(self.lignes[self.niveau]['projet'].unique())

            # Parcours points
            if not self.points[self.niveau].empty:
                projets.update(self.points[self.niveau]['projet'].unique())
            self.ListProjets = sorted(projets)
            self.nouveau.clear()
            self.nouveau.addItem("Nouveau projet")
            for p in self.ListProjets:
                self.nouveau.addItem(str(p))

    # -------------------------------------------- Comparaison ------------------------------------------------
    def set_label_precision(self):
        self.label_precision.setText(f"Précision : {self.precisions[self.horizontalSlider_precision.value()]} mm")
    
    def comparaison(self):
        conn = connecter()  # ou sélection via dialog
        if conn is None:
            print("Erreur : connexion introuvable")
            return
        precision = self.precisions[self.horizontalSlider_precision.value()]
        precision = precision * 0.001
        comparer(conn,precision)
        rafraichir()
        self.initialiser_affichage()
    
    
    def controle_admissibilite(self):
        con = connecter()
        sql = f"""
                SELECT *
                FROM  sw_pr_adm.t_pr_champobli;
                """
        df_rules=df(sql,con)
        QgsMessageLog.logMessage(f"{df_rules}", "MonPlugin", Qgis.Info)

        df_croisement= pd.DataFrame()
        for niveau in self.lignes:
            df_croisement = pd.concat([df_croisement, self.lignes[niveau]], ignore_index=True)

        for niveau in self.points:
            df_croisement = pd.concat([df_croisement, self.points[niveau]], ignore_index=True)

        for niveau in self.polygones:
            df_croisement = pd.concat([df_croisement, self.polygones[niveau]], ignore_index=True)

        # Filtrage pandas correct
        df_croisement_creation = df_croisement.loc[
            df_croisement["croisement"] == "CREATION",
            ["grpe_objet", "table_name", "gid_nouv"]
        ].copy()

        df_croisement_modification = df_croisement.loc[
            df_croisement["croisement"] == "CONSERVATION_MODIFIEE",
            ["grpe_objet", "table_name", "attributs_modif", "gid_nouv"]
        ].copy()

        croisement_creation_dict = {
            'TOPO': df_croisement_creation[df_croisement_creation["grpe_objet"] == "topo"]
                        .groupby("table_name")["gid_nouv"]
                        .agg(set)
                        .to_dict(),

            'RECOL': df_croisement_creation[df_croisement_creation["grpe_objet"] != "topo"]
                        .groupby("table_name")["gid_nouv"]
                        .agg(set)
                        .to_dict()
        }
        

        croisement_modification_dict = {
            'TOPO': df_croisement_modification[df_croisement_modification["grpe_objet"] == "topo"]
                        .groupby(["table_name","attribut_modif"])["gid_nouv"]
                        .agg(set)
                        .to_dict(),

            'RECOL': df_croisement_modification[df_croisement_modification["grpe_objet"] != "topo"]
                        .groupby(["table_name","attribut_modif"])["gid_nouv"]
                        .agg(set)
                        .to_dict()
        }
        croisement_modification_dict2 = {'TOPO':{},'RECOL':{}}
        for (table, attributs), gids in croisement_modification_dict['TOPO'].items() :
            if table not in croisement_modification_dict2['TOPO']:
                croisement_modification_dict2['TOPO'][table] = set()
            attributs = attributs.split('|')
            for attribut in attributs :
                if attribut not in croisement_modification_dict2['TOPO'][table] :
                    croisement_modification_dict2['TOPO'][table][attribut] = set()
                croisement_modification_dict2['TOPO'][table][attribut].update(gids)
                

        

        croisement_dict = {'CREATION':{'TOPO':{},'RECOL':{}},'MODIFICATION':{'TOPO':{},'RECOL':{}}}
        synthese = pd.DataFrame()
        groupe = QgsProject.instance().layerTreeRoot().findGroup(self.nouvelle_topo_group)
        if groupe:
            for layer in groupe.findLayers():
                    table_name = layer.layer().name()
                    if table_name in croisement_creation_dict['TOPO'] :
                        
                        ids = croisement_creation_dict['TOPO'][table_name]
                        cols = [field.name() for field in layer.layer().fields()]
                        data = pd.DataFrame(
                            [
                                f.attributes()
                                for f in layer.layer().getFeatures()
                                if f['gid'] in ids
                            ],
                            columns=cols
                        )
                        rules = df_rules[
                            (
                                (df_rules['nom_niveau'] == 'TOPO') |
                                (df_rules['nom_niveau'] == '<< TOUS >>')
                            )
                            &
                            (
                                (df_rules['code_objet'] == '<< TOUS >>') |
                                (table_name == 'geo_' + df_rules['code_objet'].str.lower())
                            )
                        ]
                        partie_synthese = self.layer_admissibilite( data, rules)
                        partie_synthese['schema'] = 'TOPO'
                        partie_synthese['nom_table'] = table_name
                        synthese = pd.concat([synthese, partie_synthese], ignore_index=True)
                    if table_name in croisement_modification_dict2['TOPO'] :
                        attributs = croisement_modification_dict2['TOPO'][table_name]
                        ids = set().union(*attributs.values())
                        rules = df_rules[
                            (
                                (df_rules['nom_niveau'] == 'TOPO') |
                                (df_rules['nom_niveau'] == '<< TOUS >>')


                            )
                            &
                            (
                                (df_rules['code_objet'] == '<< TOUS >>') |
                                (table_name == 'geo_' + df_rules['code_objet'].str.lower())
                            )
                            &
                            df_rules['nom_champobli'] in attributs
                        ]
                        data = pd.DataFrame(
                            [
                                f.attributes()
                                for f in layer.layer().getFeatures()
                                if f['gid'] in ids
                            ],
                            columns=cols
                        )
                        partie_synthese = self.layer_admissibilite2( data, rules)
                        partie_synthese['schema'] = 'TOPO'
                        partie_synthese['nom_table'] = table_name
                        synthese = pd.concat([synthese, partie_synthese], ignore_index=True)
        
        groupe = QgsProject.instance().layerTreeRoot().findGroup(self.nouveau_reseau_group)
        if groupe:
            for layer in groupe.findLayers():
                    table_name = layer.layer().name()
                    if table_name in croisement_creation_dict['RECOL'] :
                        
                        ids = croisement_creation_dict['RECOL'][table_name]
                        cols = [field.name() for field in layer.layer().fields()]
                        data = pd.DataFrame(
                            [
                                f.attributes()
                                for f in layer.layer().getFeatures()
                                if f['gid'] in ids
                            ],
                            columns=cols
                        )
                        rules = df_rules[
                            (
                                (df_rules['nom_niveau'] == 'RECOL') |
                                (df_rules['nom_niveau'] == '<< TOUS >>')
                            )
                            &
                            (
                                (df_rules['code_objet'] == '<< TOUS >>') |
                                (table_name == 'geo_' + df_rules['code_objet'].str.lower())
                            )
                        ]
                        partie_synthese = self.layer_admissibilite( data, rules)
                        partie_synthese['schema'] = 'RECOL'
                        partie_synthese['nom_table'] = table_name
                        synthese = pd.concat([synthese, partie_synthese], ignore_index=True)
                    if table_name in croisement_modification_dict2['RECOL'] :
                        attributs = croisement_modification_dict2['RECOL'][table_name]
                        ids = set().union(*attributs.values())
                        rules = df_rules[
                            (
                                (df_rules['nom_niveau'] == 'RECOL') |
                                (df_rules['nom_niveau'] == '<< TOUS >>')


                            )
                            &
                            (
                                (df_rules['code_objet'] == '<< TOUS >>') |
                                (table_name == 'geo_' + df_rules['code_objet'].str.lower())
                            )
                            &
                            df_rules['nom_champobli'] in attributs
                        ]
                        data = pd.DataFrame(
                            [
                                f.attributes()
                                for f in layer.layer().getFeatures()
                                if f['gid'] in ids
                            ],
                            columns=cols
                        )
                        partie_synthese = self.layer_admissibilite2( data, rules)
                        partie_synthese['schema'] = 'RECOL'
                        partie_synthese['nom_table'] = table_name
                        synthese = pd.concat([synthese, partie_synthese], ignore_index=True)
        QgsMessageLog.logMessage(f"{croisement_dict}", "MonPlugin", Qgis.Info)
    def layer_admissibilite2(self, df, attributs, df_rules) :
        data = []
        for _, rule in df_rules.iterrows():
            col_name = rule['nom_campobli'].lower()
            df = df[df['gid'] in attributs[col_name]]
            valeurs = (
                    df[col_name]
                    .value_counts(dropna=False)
                    .reset_index()
            )
            valeurs.columns = ['valeur', 'count']
            for _, valeur in valeurs.iterrows():
                if self.test(valeur['valeur'], rule['val_champobli']):
                    data.append({
                            'nom_attribut': rule['nom_champobli'],
                            'valeur_refusee': valeur['valeur'],
                            'valeurs_autorisees': rule['val_champobli'],
                            'nombre': valeur['count']
                    })


    def layer_admissibilite(self, df, df_rules):
        data = []
        for _, rule in df_rules.iterrows():
            col_name = rule['nom_campobli'].lower()
            if col_name not in df.columns:
                data.append({
                            'nom_attribut': rule['nom_champobli'],
                            'valeur_refusee': 'attribut manquant',
                            'valeurs_autorisees': rule['val_champobli'],
                            'nombre': 0
                        })
            else :
                valeurs = (
                    df[col_name]
                    .value_counts(dropna=False)
                    .reset_index()
                )
                valeurs.columns = ['valeur', 'count']
                for _, valeur in valeurs.iterrows():
                    if self.test(valeur['valeur'], rule['val_champobli']):
                        data.append({
                            'nom_attribut': rule['nom_champobli'],
                            'valeur_refusee': valeur['valeur'],
                            'valeurs_autorisees': rule['val_champobli'],
                            'nombre': valeur['count']
                        })

        return pd.DataFrame(data)

    def test (self,val, rule) :
        if rule == 'NON NUL':
            if val is not None :
                return False
            else :
                return True
        else :
            rule = rule.split("|")
            if val in rule :
                return False
            else :
                return True




    # ---------------------------------------------------- Close -----------------------------------------------
    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
